# Generated by Django 4.0.4 on 2022-05-31 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('st_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='degree',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='st_app.degree'),
        ),
    ]
