# Generated by Django 4.0.4 on 2022-05-31 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('st_app', '0002_alter_students_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='degree',
        ),
    ]
